<?php
/**
 * Cart2Quote
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->get('Bss\AdvancedHidePrice\Helper\Data');
$_product = $block->getProduct(); 
?>

<?php if ($helper->activeCallHidePrice($_product) == 'callforprice') : //Show Callforprice ?>
    <div class="callforprice-container box-tocart">
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Bss_AdvancedHidePrice::css/styles.css') ?>">
        <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
        <a class="callforprice_clickme action primary tocart"><?php echo $helper->getCallforpriceText($_product) ?></a>
    </div>
    <script>
        require([
            "jquery",
            "domReady!"
        ], function ($) {
            $('#product_addtocart_form').attr('action', '');
            var product = $('.callforprice-container input[name="product"]')
            $('.callforprice_request .product_ids').val(product);
        });
    </script>
<?php elseif($helper->activeCallHidePrice($_product) == 'hideprice') : ?>
    <h1 class="callforprice_text"><?php echo $helper->getCallforpriceText($_product) ?></h1>
<?php else : ?>
	<?php $quoteButton = $block->addChild('quote_button', 'Cart2Quote\Quotation\Block\Button'); ?>
	<?php $cartButtonTitle = __('Add to Cart'); ?>
	<?php $quoteButtonTitle = __('Add to Quote'); ?>
	<?php $validators = $block->escapeHtml(json_encode($block->getQuantityValidators())); ?>

	<div class="actions-container">
	<?php if ($_product->isSaleable() || $quoteButton->showQuoteButton()) : ?>
		<div class="box-tocart">
			<fieldset class="fieldset">

				<?php if ($block->shouldRenderQuantity()) : ?>
					<!-- Qty start -->
					<div class="field qty">
						<label class="label" for="qty"><span><?php echo __('Qty') ?></span></label>

						<div class="control">
							<input type="number"
								   name="qty"
								   id="qty"
								   maxlength="12"
								   value="<?php echo $block->getProductDefaultQty() * 1 ?>"
								   title="<?php echo __('Qty') ?>" class="input-text qty"
								   data-validate="<?php echo $validators ?>"
								/>
						</div>
					</div>
					<!-- Qty stop -->
				<?php endif; ?>

				<div class="actions">

					<?php if ($_product->isSaleable()) : ?>
						<!-- Cart button start -->
						<button type="submit"
								title="<?php echo $cartButtonTitle ?>"
								class="action primary tocart"
								id="product-addtocart-button">
							<span><?php echo $cartButtonTitle ?></span>
						</button>
						<!-- Cart button stop -->
					<?php endif; ?>
					<?php if ($quoteButton->showQuoteButton() && !$quoteButton->showMessageNotLoggedIn()) : ?>
						<!-- Quote button start -->
						<button type="submit"
								title="<?php echo $quoteButtonTitle ?>"
								class="action tocart"
								id="product-addtoquote-button">
							<span><?php echo $quoteButtonTitle ?></span>
						</button>
						<!-- Quote button stop -->
					<?php elseif ($quoteButton->showMessageNotLoggedIn()) : ?>
						<button id="product-addtoquote-button" disabled="disabled" class="action tocart">
							<span><?php echo __('Please login to add to Quote.'); ?></span>
						</button>
					<?php endif; ?>

					<?php echo $block->getChildHtml('', true) ?>
				</div>
			</fieldset>
		</div>
	<?php endif; ?>

	<?php
		$objectManager = \Magento\Framework\App\ObjectManager::getInstance();	
		$productHelper = $objectManager->create('Alpha\Productfavourites\Helper\Data');
		$arrs = $productHelper->toOptionArray();
		$rent_try_buy = 0;
		$lease = 0;
		
		$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
		$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
		if($_product->getPrice() && $_product->isSaleable()){
			if($_product->getSpecialPrice()){
				$rent_try_buy = round($_product->getSpecialPrice()*(0.055)*(12/52),2);
				foreach ($arrs as $key => $val){
					if($key == 0 && $_product->getSpecialPrice() > $val['value']){
						$lease = round($_product->getSpecialPrice()*$val['percent']*(12/52),2);
					}else{
						if($_product->getSpecialPrice() <= $val['value']){
							$lease = round($_product->getSpecialPrice()*$val['percent']*(12/52),2);
						}
					}
				}
			}else{
				$rent_try_buy = round($_product->getPrice()*(0.055)*(12/52),2);
				foreach ($arrs as $key => $val){
					if($key == 0 && $_product->getPrice() > $val['value']){
						$lease = round($_product->getPrice()*$val['percent']*(12/52),2);
					}else{
						if($_product->getPrice() <= $val['value']){
							$lease = round($_product->getPrice()*$val['percent']*(12/52),2);
						}
					}
				}
			}
		}
	?>

	<div class="finance-options">
		<?php if($rent_try_buy): ?>
			<div class="item rent-try-buy">
				<div class="img-finance-options">
					<a href="<?php echo $this->getUrl('silver-chef-rent-try-buy'); ?>">
						<img src="<?php echo $block->getViewFileUrl('images/rent_try_buy.png'); ?>"/>
					</a>
				</div>
				<div class="info-finance-options">
					<div class="title"><?php echo __('rent-try-buy');?></div>
					<div class="price"><span><?php echo $priceHelper->currency(number_format($rent_try_buy,2), true, false); ?> <span><?php echo __('+GST /WK*');?></span></span></div>
					<div class="descr"><?php echo __('Based on 12-month contract')?></div>
				</div>
			</div>
		<?php endif; ?>
		<?php if($lease): ?>
			<div class="item lease">
				<div class="img-finance-options"><a><img src="<?php echo $block->getViewFileUrl('images/lease.png'); ?>"/></a></div>
				<div class="info-finance-options">
					<div class="title"><?php echo __('Lease From')?></div>
					<div class="price"><span><?php echo $priceHelper->currency(number_format($lease,2), true, false); ?> <span><?php echo __('+GST /WK*');?></span></span></div>
					<div class="descr"><?php echo __('Based on 24-month contract')?></div>
				</div>
			</div>
		<?php endif; ?>
	</div>
	</div>

	<?php if ($block->isRedirectToCartEnabled()) : ?>
		<script>
			require([
				'jquery',
				'mage/mage',
				'Magento_Catalog/product/view/validation',
				'Cart2Quote_Quotation/js/catalog-add-to-cart'
			], function ($) {
				'use strict';
				var addToQuote = false;
				$('#product-addtoquote-button').click(function (e) {
					addToQuote = "<?php echo $block->getBaseUrl().'quotation/quote/add' ?>";
				});

				$('#product_addtocart_form').mage('validation', {
					radioCheckboxClosest: '.nested',
					submitHandler: function (form) {
						var widget = $(form).quotationAddToCart({
							quoteFormUrl: addToQuote,
							bindSubmit: false,
							noAjax: false
						});

						widget.quotationAddToCart('submitForm', $(form));
						addToQuote = false;
						return false;
					}
				});
			});
		</script>
	<?php else : ?>
		<script>
			require([
				'jquery',
				'mage/mage',
				'Magento_Catalog/product/view/validation',
				'Cart2Quote_Quotation/js/catalog-add-to-cart'
			], function ($) {
				'use strict';
				var addToQuote = false;
				$('#product-addtoquote-button').click(function (e) {
					addToQuote = "<?php echo $block->getBaseUrl().'quotation/quote/add' ?>";
				});

				$('#product_addtocart_form').mage('validation', {
					radioCheckboxClosest: '.nested',
					submitHandler: function (form) {
						var widget = $(form).quotationAddToCart({
							quoteFormUrl: addToQuote,
							bindSubmit: false
						});

						widget.quotationAddToCart('submitForm', $(form));
						addToQuote = false;
						return false;
					}
				});
			});
		</script>
	<?php endif; ?>
<?php endif ?>