<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**  @var $block \Magento\Checkout\Block\Cart */
?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<?php echo $block->getChildHtml('quote.summary') ?>
<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('checkout/cart/updatePost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'
          class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption role="heading" aria-level="2" class="table-caption"><?php /* @escapeNotVerified */ echo __('Shopping Cart Items') ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?php /* @escapeNotVerified */ echo __('Product Name') ?></span></th>
                    <th class="col price" scope="col"><span><?php /* @escapeNotVerified */ echo __('Unit Price') ?></span></th>
                    <th class="col qty" scope="col"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></th>
                    <th class="col subtotal" scope="col"><span><?php /* @escapeNotVerified */ echo __('Subtotal') ?></span></th>
                    <th class="col silver-chef" scope="col"><img src="<?php echo $block->getViewFileUrl('images/silver-chef-logo.png'); ?>" alt=""/><span><strong><?php /* @escapeNotVerified */ echo __('Silver Chef') ?></strong> <?php /* @escapeNotVerified */ echo __('Rent - Try - Buy') ?></span></th>
                    <th class="col actions" scope="col">&nbsp;</th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item): ?>
                <?php echo $block->getItemHtml($_item) ?>
            <?php endforeach ?>
			
        </table>
		<div class="cart item-action">
			<div class="item-info">
				<div class="btn-actions">
					<div class="cart main actions">
						<?php if ($block->getContinueShoppingUrl()): ?>
							<a class="action continue"
							   href="<?php echo $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
							   title="<?php echo $block->escapeHtml(__('Continue Shopping')); ?>">
								<span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
							</a>
						<?php endif; ?>
						<button type="submit"
								name="update_cart_action"
								data-cart-empty=""
								value="empty_cart"
								title="<?php echo $block->escapeHtml(__('Clear Shopping Cart')); ?>"
								class="action clear" id="empty_cart_button">
							<span><?php /* @escapeNotVerified */ echo __('Clear Shopping Cart'); ?></span>
						</button>
						<button type="submit"
								name="update_cart_action"
								data-cart-item-update=""
								value="update_qty"
								title="<?php echo $block->escapeHtml(__('Update Shopping Cart')); ?>"
								class="action update">
							<span><?php /* @escapeNotVerified */ echo __('Update Shopping Cart'); ?></span>
						</button>
						<a href="<?php echo $this->getUrl('quotation/copytoquote'); ?>">
							<button type="button"
									name="copy_to_quote_action"
									value="copy_to_quote"
									title="<?php echo $block->escapeHtml(__('Copy to Quotation')); ?>"
									class="action copytoquote"
								>
								<span><?php echo __('Copy to Quotation'); ?></span>
							</button>
						</a>
						<input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
					</div>
				</div>
				<div class="cart-totals" >
					<?php echo $block->getChildHtml('checkout.cart.totals') ?>
					<?php echo $block->getChildHtml('checkout.cart.methods.bottom') ?>
				</div>
				<div class="silver-chef-total">
					<?php 
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$cart = $objectManager->get('\Magento\Checkout\Model\Cart'); 

						// retrieve quote items collection
						$itemsCollection = $cart->getQuote()->getItemsCollection();

						// get array of all items what can be display directly
						$itemsVisible = $cart->getQuote()->getAllVisibleItems();

						// retrieve quote items array
						$items = $cart->getQuote()->getAllItems();

						$totalSilverChef = 0;
						foreach($items as $item) {
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();	
							$rent_try_buy = 0;	
							$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
							$_product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
							if($_product->getPrice() && $_product->isSaleable()){
								if($_product->getSpecialPrice()){
									$rent_try_buy = round($_product->getSpecialPrice()*(0.055)*(12/52),2);
								} else {
									$rent_try_buy = round($_product->getPrice()*(0.055)*(12/52),2);
								}
							}  
							$totalSilverChef += $rent_try_buy;
						}
					?>
					<div class="silver-chef-total">
						<div class="totals sub"><?php echo $priceHelper->currency(number_format($totalSilverChef,2), true, false); ?></div>
						<div class="grand totals"><?php echo $priceHelper->currency(number_format($totalSilverChef,2), true, false); ?></div>
					</div>
					<button type="button" title="Silver Chef" class="action primary silverchef">
						<span><?php echo __('SilverChef'); ?></span>
					</button>
				</div>
			</div>
		</div>
    </div>
</form>

<?php echo $block->getChildHtml('checkout.cart.order.actions') ?>
<?php echo $block->getChildHtml('coupon') ?>
<?php echo $block->getChildHtml('shopping.cart.table.after'); ?>