<?php
/**
 * Cart2Quote
 */

/**  @var $block \Cart2Quote\Quotation\Block\Quote */
?>
<?php $form = $block->getForm(); ?>
<?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
<?php echo $block->getChildHtml('form_before') ?>
<form action="<?php echo $block->getUrl('quotation/quote/updatePost') ?>" method="post" id="form-validate"
      data-mage-init='{"validation":{}}' class="form form-cart">
    <?php echo $block->getBlockHtml('formkey'); ?>
    <?php echo $block->getChildHtml('quotation.quote.customer.note') ?>

    <div class="cart table-wrapper<?php echo $mergedCells == 2 ? ' detailed' : ''; ?>">
        <table id="shopping-cart-table" class="cart items data table">
            <caption role="heading" aria-level="2" class="table-caption"><?php echo __('Quote Items') ?></caption>
            <thead>
            <tr>
                <th class="col item" scope="col"><span><?php echo __('Product Name') ?></span></th>
                <th class="col price" scope="col"><span><?php echo __('Unit Price') ?></span></th>
                <th class="col qty" scope="col"><span><?php echo __('Quantity') ?></span></th>
                <th class="col actions" scope="col">&nbsp;</th>
            </tr>
            </thead>

            <?php foreach ($block->getItems() as $_item) : ?>
				<?php echo $block->getItemHtml($_item) ?>
			<?php endforeach ?>

            <div class="cart main actions">
                <td colspan="4">
                    <div class="quote-actions">
                        <button type="submit" name="update_quote_action" value="empty_quote"
                                title="<?php echo $block->escapeHtml(__('Clear Quote')); ?>" class="action clear"
                                id="empty_quote_button" style="margin: 10px 0 0 0;">
                            <span><?php echo __('Clear Quote'); ?></span>
                        </button>
                        <button type="submit" name="update_quote_action" value="update_qty"
                                title="<?php echo $block->escapeHtml(__('Update Quote')); ?>" class="action update"
                                style="margin: 10px 0 0 0;">
                            <span><?php echo __('Update Quote'); ?></span>
                        </button>
                    </div>
                </td>
            </div>
        </table>
    </div>
</form>
<?php echo $block->getChildHtml('quotation.quote.order.actions') ?>
<?php echo $block->getChildHtml('quotation.quote.table.after'); ?>
<?php echo $form; ?>

