<?php
/**
 * Cart2Quote
 */

/** @var $block \Cart2Quote\Quotation\Block\Quote\Sidebar */
?>
<?php if ($block->getIsQuotationEnabled()) : ?>
<div data-block="miniquote" class="miniquote-wrapper" style="<?php echo $block->getExtraCSS(); ?>">
    <a class="action showquote" href="<?php echo $block->getQuoteCartUrl(); ?>"
       data-bind="scope: 'miniquote_content'">
        <span class="text"><?php echo __('Quote'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: quote().summary_count == 0 }, blockLoader: isLoading">
            <span class="counter-number"><!-- ko text: quote().summary_count --><!-- /ko --> <span class="item-empty"><?php /* @escapeNotVerified */ echo __('item'); ?></span></span>
            <span class="counter-label">
            <!-- ko if: quote().summary_count -->
                <!-- ko text: quote().summary_count --><!-- /ko -->
                <!-- ko text: $t('items') --><!-- /ko -->
            <!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()) : ?>
        <div class="block block-miniquote empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=miniquote]",
                "triggerTarget":".showquote",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="miniquote-content-wrapper" data-bind="scope: 'miniquote_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script>
        window.quotation = <?php echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='miniquote']": {
            "Magento_Ui/js/core/app": <?php echo $block->getJsLayout(); ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }



    </script>
</div>
<?php endif; ?>


