<?php
use Magento\Framework\App\Action\Action;
$categoryId = $this->getCategoryId();
$_productCollection = $block->getCategoryProducts($categoryId);
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div></div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>

    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $currentCateg = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
    $categoryHelper = $objectManager->get('Magento\Catalog\Helper\Category');
    ?>
    <?php if($currentCateg): ?>
        <?php
        $obj = \Magento\Framework\App\ObjectManager::getInstance()->create('\Magento\Catalog\Api\CategoryManagementInterface');
        $currentCateg = $currentCateg->getId(); //parent category
        $depth = 1;

        /** @var \Magento\Catalog\Api\Data\CategoryTreeInterface $subCategs */
        $subCategs = $obj->getTree($currentCateg, $depth);
        ?>
        <ul class="subchildrens">
            <?php foreach($subCategs->getChildrenData() as $childrenCategory): ?>
                <?php
                if (!$childrenCategory->getIsActive()) {
                    continue;
                }
                ?>
                <li>
                    <a href="<?php echo $categoryHelper->getCategoryUrl($childrenCategory) ?>"><?php echo $childrenCategory->getName() ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="products list items product-items product-carosel" id="pro-owl-<?php echo $categoryId; ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>


                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>
                        <div class="product-options-wrapper" id="product-options-wrapper">
                            <?php if ($swatchoptionsBlock = $block->getChildBlock($_product->getTypeId() . '_feature_swatch_prototype'.$this->getCategoryId())): ?>
                                <?php echo $swatchoptionsBlock->setProduct($_product)->toHtml(); ?>
                            <?php endif; ?>
                        </div>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>"
                                                    class="action tocart primary"
                                                    data-ptype="<?php echo $_product->getTypeId() == 'giftvoucher' ? 'giftvoucher' : '' ?>"
                                                    data-purl="<?php echo $_product->getProductUrl() ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Bag') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script>
    require(
        [
            'jquery',
            'carousel'
        ],
        function ($) {
            $(document).ready(function () {
                $('#pro-owl-<?php echo $categoryId; ?>').owlCarousel({
                    // autoPlay: 3000, //Set AutoPlay to 3 seconds

                    items : 5,
                    itemsDesktop : [1199,5],
                    itemsDesktopSmall : [979,5],
                    paginationNumbers: false,
                    dots: false,
                    navigation: true,
                    navigationText: [
                        "<i class='fa fa-chevron-left'></i>",
                        "<i class='fa fa-chevron-right'></i>"
                    ]
                });

                /*setTimeout(function(){
                    $('.tab-content').css('display','none');
                }, 2000);*/

            });
        }
    );
</script>