<?php
	use Magento\Framework\App\Action\Action;
	$categoryId = $this->getCategoryId();
	$_productCollection = $block->getCategoryProducts($categoryId);
	$_helper = $this->helper('Magento\Catalog\Helper\Output');

	$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$object_manager = $_objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
	$categUrl = $object_manager->getUrl();

	$cartButtonTitle = __('Add to Cart'); 
	$quoteButtonTitle = __('Add to Quote'); 
	$quoteCondition = 'cart2quote_quotation/global/show_btn_list'; 
	$buttonBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Cart2Quote\Quotation\Block\Button'); 
?>
<?php if (!$_productCollection->count()): ?>
    <div></div>
<?php else: ?>
	<div class="special-products">
		<?php echo $block->getAdditionalHtml() ?>
		<div class="block-title-name"><?php echo __('<strong>Our</strong> Specials'); ?></div>
		<?php
		$viewMode = 'grid';
		$image = 'category_page_grid';
		$showDescription = false;
		$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

		/**
		 * Position for actions regarding image size changing in vde if needed
		 */
		$pos = $block->getPositioned();
		?>
		<div class="<?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
			<?php $iterator = 1; ?>
			<div class="items product-items product-carosel" id="pro-owl-<?php echo $categoryId; ?>">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<div class="item product product-item">' : '</div><div class="item product product-item">' ?>
					<div class="product-item-info" data-container="product-grid">
						<?php
						$productImage = $block->getImage($_product, $image);
						if ($pos != null) {
							$position = ' style="left:' . $productImage->getWidth() . 'px;'
								. 'top:' . $productImage->getHeight() . 'px;"';
						}
						$badge= $_product->getResource()->getAttribute('badge')->getFrontend()->getValue($_product);
						?>
						<?php // Product Image ?>
						<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
							<div class="product-badge <?php echo $badge; ?>">&nbsp;</div>
							<?php echo $productImage->toHtml(); ?>
						</a>


						<div class="product details product-item-details">
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
							<strong class="product name product-item-name">
								<a class="product-item-link"
								   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
									<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</strong>
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
							<?php echo $block->getProductDetailsHtml($_product); ?>

							<div class="product-item-inner">
								<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($_product->isSaleable() || $buttonBlock->showQuoteButton($quoteCondition)) : ?>
											<!-- Cart button start -->
											<?php if ($_product->isSaleable()) : ?>
												<?php $postParamsCart = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php echo $postParamsCart['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php echo $postParamsCart['data']['product']; ?>">
													<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>"
														   value="<?php echo $postParamsCart['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtml($cartButtonTitle); ?>"
															class="action tocart primary">
														<span><?php echo $cartButtonTitle ?></span>
													</button>
												</form>
											<?php endif; ?>
											<!-- Cart button stop -->
								
											<!-- Quote button start -->
											<?php if ($buttonBlock->showQuoteButton($quoteCondition)) : ?>
												<?php $postParamsQuote = $buttonBlock->getAddToQuotePostParams($_product); ?>
												<form data-role="toquote-form" action="<?php echo $postParamsQuote['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php echo $postParamsQuote['data']['product']; ?>">
													<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>"
														   value="<?php echo $postParamsQuote['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<button type="submit"
															title="<?php echo $block->escapeHtml($quoteButtonTitle); ?>"
															class="action tocart">
														<span><?php echo $quoteButtonTitle ?></span>
													</button>

												</form>
											<?php endif; ?>
											<!-- Quote button stop -->

										<?php else : ?>
											<?php if ($_product->getIsSalable()) : ?>
												<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else : ?>
												<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
								</div>
							</div>
						</div>
					</div>
					<?php echo($iterator == count($_productCollection)+1) ? '</div>' : '' ?>
					<?php //if($iterator == 6) break; ?>
				<?php endforeach; ?>
			</div>
		</div>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
        </script>
		<script type="text/x-magento-init">
			{
				"[data-role=toquote-form], .form.map.checkout": {
					"catalogAddToCart": {
							"addToCartButtonTextDefault": "<?php echo __('Add to Quote') ?>",
							"addToCartButtonTextWhileAdding": "<?php echo __('Adding to Quote...') ?>",
							"minicartSelector": "[data-block=\"miniquote\"]"
					}
				}
			}
        </script>
    <?php endif; ?>
<?php endif; ?>