<?php
/**
 * Cart2Quote
 */
?>
<?php
/**
 * Product list template
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->get('Bss\AdvancedHidePrice\Helper\Data');
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_productCollectionCount = $_productCollection->getSize();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollectionCount) : ?>
    <div class="message info empty">
        <div><?php echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $position = '';
    ?>
    <div class="products wrapper <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
				<?php 
					$objectManager =   \Magento\Framework\App\ObjectManager::getInstance();
					$productData = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
				?>
                <?php
                if ($iterator++ == 1) {
                    echo '<li class="item product product-item">';
                } else {
                    echo '</li><li class="item product product-item">';
                }
                ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
					$badge= $_product->getResource()->getAttribute('badge')->getFrontend()->getValue($_product);
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php echo $_product->getProductUrl() ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <div class="product-badge <?php echo $badge; ?>">&nbsp;</div>
						<?php echo $productImage->toHtml(); ?>
                    </a>

                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php echo $_product->getProductUrl() ?>">
                                <?php echo $_helper->productAttribute($productData, $productData->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
						<?php if(!$helper->activeCallHidePrice($_product)) : ?>
							<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php endif ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php //Callforprice condition ?>
                                    <?php if(!$helper->activeCallHidePrice($_product)) : ?>
                                        <!-- Cart2Quote Overwrite Start -->
										<?php
										echo $block->getChildBlock('addtocart.addtoquote')
											->setListProduct($_product)
											->setCacheLifeTime(null)
											->toHtml();
										?>
										<!-- Cart2Quote Overwrite Stop -->
                                    <?php else : ?>
                                        <?php if($helper->activeCallHidePrice($_product) == 'callforprice') : ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <div class="callforprice-container">
                                                <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Bss_AdvancedHidePrice::css/styles.css') ?>">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <a class="callforprice_clickme action primary tocart"><?php echo $helper->getCallforpriceText($_product) ?></a>
                                            </div>
                                            <script>
                                                require([
                                                    "jquery",
                                                    "domReady!"
                                                ], function ($) {
                                                    $('#product_addtocart_form').attr('action', '');
                                                });
                                            </script>
                                        <?php else : ?>
                                            <p class="callforprice_text"><?php echo $helper->getCallforpriceText($_product); ?></p>
                                        <?php endif ?>
                                    <?php endif ?>
                                    <?php //End Callforprice condition ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos,
                                    $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span><?php echo __('Add to Compare') ?></span>
                                    </a>
                                </div>
                            </div>
                            <?php if ($showDescription) : ?>
                                <div class="product description product-item-description">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(),
                                        'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped ?>"
                                       class="action more"><?php echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo ($iterator == $_productCollectionCount + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="bottom-toolbar">
    <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
			{
				"[data-role=tocart-form], .form.map.checkout": {
					"catalogAddToCart": {}
				}
			}
        </script>
        <script type="text/x-magento-init">
			{
				"[data-role=toquote-form], .form.map.checkout": {
					"catalogAddToCart": {
							"addToCartButtonTextDefault": "<?php echo __('Add to Quote') ?>",
							"addToCartButtonTextWhileAdding": "<?php echo __('Adding to Quote...') ?>",
							"minicartSelector": "[data-block=\"miniquote\"]"
					}
				}
			}
        </script>
    <?php endif; ?>
<?php endif; ?>
