<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

$productId = $block->getSaleableItem()->getId();

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php 
	$objectManager =   \Magento\Framework\App\ObjectManager::getInstance();
	$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
	$productData = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
	$rrpPrice = (float)$productData->getPrice();
	$specialPrice = (float)$productData->getSpecialPrice();
	$yousave = 0;
	if($rrpPrice > 0 && $specialPrice > 0 && $specialPrice < $rrpPrice) {
		$yousave = number_format((float)($rrpPrice - $specialPrice), 2, '.', ''); 
	}
?>

<?php if ($yousave > 0): ?>
	<span class="old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('RRP:'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
	<span class="special-price">
		<span class="price-container price-final_price tax weee">
            <span class="price-label"><?php echo __('Special Price'); ?></span>
			<span id="product-price-7085" data-price-amount="<?php echo number_format((float)($specialPrice), 2, '.', ''); ?>" data-price-type="finalPrice" class="price-wrapper ">
				<span class="price"><?php echo $priceHelper->currency($specialPrice, true, false); ?></span>    
			</span>
        </span>
    </span>
	<?php if($yousave > 0): ?>
		<span class="save-price"><?php echo $block->escapeHtml(__('SAVE:')); ?> <span class="s-price"><?php echo $priceHelper->currency($yousave, true, false); ?></span></span>
	<?php endif; ?>
<?php else: ?>
	<span class="old-price">&nbsp;</span>
	<span class="special-price one-price">
		<?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
			'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
			'price_type'        => 'finalPrice',
			'include_container' => true,
			'schema' => $schema
		]); ?>
	</span>
	<span class="save-price">&nbsp;</span>
<?php endif; ?>
