<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-518cc816521eb304"></script> 

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<div class="product_socialsharebutton"><span class="share_text"><?php echo __('Share: '); ?></span><div class="addthis_inline_share_toolbox_m97n"></div></div>