<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="sidebar sidebar-main">
	<div id="layered-filter-block" class="block filter" data-collapsible="true">
		<div class="block-content filter-content"></div>
	</div>
</div>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products toolbar-top" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
	
		<?php //include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/attributes.phtml')) ?>

        <?php //include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>

        <?php echo $block->getPagerHtml() ?>
		<div class="right-toolbar">
        <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
		<?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>  
        </div>  
    </div>

	
<?php endif ?>
