<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="block newsletter">
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
			<div class="title"><?php /* @escapeNotVerified */ echo __('Sign up to get the latest') ?><br/><span class="promotions"><?php /* @escapeNotVerified */ echo __('Promotions and Deals') ?>!</span></div>
			<div class="field name">
                <div class="control">
                    <input name="subscriber_name" type="text"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Name') ?>"
                                data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field newsletter">
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Email') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
			<div class="field post-code">
                <div class="control">
                    <input name="subscriber_postcode" type="text"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Post Code') ?>"
                                />
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Subscribe Me') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
